// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Put_your_API_key_here',
    appId: '1:1050817219071:web:072846bffa1b197be67fca',
    messagingSenderId: '1050817219071',
    projectId: 'flare-9b5ed',
    authDomain: 'flare-9b5ed.firebaseapp.com',
    storageBucket: 'flare-9b5ed.firebasestorage.app',
    measurementId: 'G-NK1NNG008X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Put_your_API_key_here',
    appId: '1:1050817219071:android:c2ee0dfb6a7dd2c4e67fca',
    messagingSenderId: '1050817219071',
    projectId: 'flare-9b5ed',
    storageBucket: 'flare-9b5ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Put_your_API_key_here',
    appId: '1:1050817219071:ios:a2348a440caf278ee67fca',
    messagingSenderId: '1050817219071',
    projectId: 'flare-9b5ed',
    storageBucket: 'flare-9b5ed.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Put_your_API_key_here',
    appId: '1:1050817219071:ios:a2348a440caf278ee67fca',
    messagingSenderId: '1050817219071',
    projectId: 'flare-9b5ed',
    storageBucket: 'flare-9b5ed.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Put_your_API_key_here',
    appId: '1:1050817219071:web:20eb68ded974d659e67fca',
    messagingSenderId: '1050817219071',
    projectId: 'flare-9b5ed',
    authDomain: 'flare-9b5ed.firebaseapp.com',
    storageBucket: 'flare-9b5ed.firebasestorage.app',
    measurementId: 'G-W3X63T73KH',
  );
}
